### ISSUE TITLE
How to skip a method from gems?

### ISSUE THREAD

**Issue by khrisnagunanasurya** [pocke/rbs_rails#230]
Hi, I have a problem with how to mock/ignore the classes or methods from gems, I use a gem called [AASM](https://github.com/aasm/aasm), where when we include the AASM into the model, we can use the helper method like `aasm`, `transitions`, ... etc.
But I'm unable to make RBS ignore those methods or try to mock them inside RBS. can someone help me with this?

What I've been trying so far
```
  class History < ::ApplicationRecord
    ...

    module AasmGem
      module ClassMethods
        def aasm: (*untyped) { () -> void } -> void

        def event: (Symbol) -> void

        def transitions: (from: Symbol, to: Symbol) -> void
    end
    include AasmGem

    ...
  end
```

**Comment by ksss** [comment]
How about to use `extend` instead of `include`?

```diff
- include AasmGem
+ extend AasmGem::ClassMethods
```

**Comment by khrisnagunanasurya** [comment]
Thanks, it's working
