### ISSUE TITLE
How to fix `NameError: uninitialized constant Star::Notification`

### ISSUE THREAD

**Issue by tanmoysrt** [pocke/rbs_rails#260]
While executing ` ./bin/rails rbs_rails:generate_rbs_for_models ` facing `NameError: uninitialized constant Star::Notification` issue

Full trace log -
```
[DEPRECATION] Rack::Attack.throttled_response is deprecated. Please use Rack::Attack.throttled_responder instead
rails aborted!
NameError: Rails couldn't find a valid model for Notification association. Please provide the :class_name option on the association declaration. If :class_name is already provided, make sure it's an ActiveRecord::Base subclass.

          raise NameError, msg
          ^^^^^
/home/tanmoy/Desktop/oss/CircuitVerse/bin/rails:9:in `<top (required)>'
/home/tanmoy/Desktop/oss/CircuitVerse/bin/spring:15:in `<top (required)>'

Caused by:
NameError: uninitialized constant Star::Notification

            raise NameError.new("uninitialized constant #{candidates.first}", candidates.first)
            ^^^^^
/home/tanmoy/Desktop/oss/CircuitVerse/bin/rails:9:in `<top (required)>'
/home/tanmoy/Desktop/oss/CircuitVerse/bin/spring:15:in `<top (required)>'
Tasks: TOP => rbs_rails:generate_rbs_for_models
(See full trace by running task with --trace)

```

You can check the model here -
https://github.com/CircuitVerse/CircuitVerse/blob/master/app/models/star.rb
https://github.com/CircuitVerse/CircuitVerse/blob/master/app/models/project.rb

----

Notification model has a polymorphic association with star and project model
```ruby
class PopulateNoticedNotificationsTable < ActiveRecord::DataMigration
  class Notification < ActiveRecord::Base
    belongs_to :notifiable, polymorphic: true
  end

  def up
    Notification.where(migrated: false).find_each do |notification|
      NoticedNotification.transaction do
        new_notification = NoticedNotification.create!(
          :recipient_type => notification.target_type,
          :recipient_id => notification.target_id,
          :type => (notification.notifiable_type == "Star" ? "StarNotification" : "ForkNotification"),
          :params => {
            user_id: notification.notifier_id,
            project_id: (notification.notifiable_type == "Star" ? notification.notifiable.project_id : notification.notifiable.forked_project_id)
          },
          :read_at => notification.opened_at
        )
        notification.update(migrated: true)
      end
      rescue StandardError => e
        Rails.logger.info e.message
    end
  end
end
```
How to fix this ?

**Comment by tanmoysrt** [comment]
@pocke can you take a look if this issue can be solved? I am not able to find solution

**Comment by pocke** [comment]
Usually this error occurs on an invalid association. For example

```ruby
class Blog
  # It has a typo. Artice model does not exist, so it raises the error
  has_many :articles

  # User model does not exist., so it raises the error
  has_many :users
end

class Article
end
```

Could you check whether your application has an invalid association or not?


> Notification model has a polymorphic association with star and project model


Currently, RBS Rails is not tested on polymorphic association. It may not support polymorphic association. Could you make a minimum repository to reproduce the problem?

**Comment by ksss** [comment]
@tanmoysrt Hi, I'm one of those who are concerned about this issue.
I feel this is an extensibility issue in rbs_rails.

## Reason for error

rbs_rails use `ActiveRecord::Reflection::MacroReflection#klass`.

https://github.com/pocke/rbs_rails/blob/4ba3f0fa61f961590213cc04e83a5433166691ed/lib/rbs_rails/active_record.rb#L127

This method attempts to get a class object from a given symbol name.
Therefore, an error seems to be occurring here.

This is a necessary method for reliable name resolution, but if we want it to work even if there is a non-existent association, we will need to rescue `NameError` and continue.

## Extensibility issue

So `has_noticed_notifications` generates a method like `notifications_as_*`, but the type information for this method is not generated.

Currently, rbs_rails does not support ActiveRecord extension gems such as Noticed gem.

I would like to ask @pocke.
Do you plan to support ActiveRecord extension gems like the Noticed gem in rbs_rails?

**Comment by tanmoysrt** [comment]
@ksss thanks for your solution.

However in my case the main issue was little bit different.
We previously used ActionMailer , so there was already a table `Notifications` in database. Noticed gem's default table is also `Notifications.` While upgrading we don't want to delete that table. So we use

```
has_many :notifications
has_noticed_notifications model_name: "NoticedNotification"
```
 to override the default table. 

But as there was no `Notification` class it was constantly failing to generate rbs for some reason, for that, so the workaround was, create a `NoticedNotification` Class
```ruby
class NoticedNotification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end
```

and 

```ruby
has_many :noticed_notifications
has_noticed_notifications model_name: "NoticedNotification"
```

It fixes the issue.

---

However, I previously though rbs_rails has issue with polymorphic association, later found it doesn't have any issue regarding that

**Comment by pocke** [comment]
## Short Summary

I think we need a plugin system for RBS Rails, but the priority to implement it is low. 


## Details


I think RBS Rails needs more extensibility because Rails has extensibility. There are many gems extending Rails and Active Record.

I do not want to implement this extension support into RBS Rails directly. For example, adding support for the `has_noticed_notifications` method to RBS Rails. There are so many Rails extension gems, so RBS Rails will become fat if we implement the support into RBS Rails.


I'd like to implement a plugin system instead of supporting gems directly. For example, we can add some hooks (`before_*` and `after_*`) or some configurations. But I haven't designed the system.


However I'd like to work on other problems for now, so I do not have the capacity to tackle this feature.
And I guess we haven't corrected plugin use cases enough.

**Comment by ksss** [comment]
@pocke Thank you for responding.
I agree with that you. Glad to know the current status.

**Comment by tanmoysrt** [comment]
@pocke Thank you for the update !
