### ISSUE TITLE
Has gem_rbs_collection made this project redundant?

### ISSUE THREAD

**Issue by franco-reyes** [pocke/rbs_rails#282]
Is this repo still active? I've noticed that the the active gems are available in https://github.com/ruby/gem_rbs_collection/tree/main/gems and that this repo hasn't been updated in a year. Should we be using gem_rbs_collection to use RBS with Rails?

**Comment by pocke** [comment]
gem_rbs_collection provides static RBS files for Rails gems. This repository dynamically generates RBS files from the application code. They have different roles.
